### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by nazmussakib44** [trek-view/nadir-patcher#5]
staring...
Traceback (most recent call last):
  File "C:\xampp\htdocs\nadir-patcher-master\nadir-patcher.py", line 256, in <module>
    main(sys.argv[1:])
  File "C:\xampp\htdocs\nadir-patcher-master\nadir-patcher.py", line 65, in main     
    first_s = get_res(file_list[0])
  File "C:\xampp\htdocs\nadir-patcher-master\nadir-patcher.py", line 222, in get_res
    ffprobe_output = subprocess.check_output(args).decode('utf-8')
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by MobiGA** [comment]
I seem to have the same problem. What may have went wrong?

**Comment by himynamesdave** [comment]
the error is

```
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

can you share the input command here @nazmussakib44 @MobiGA ?

E.g.

```shell
python3 nadir-patcher.py samples\input\GSAA7468.JPG nadir-library\trek_view_full_nadir.png 25 samples\output\
```
Note, depending on permissions, the directory used to output might need to be created before the script run. (e.g. in the above example I would create `samples\output\` before running the script)
